### ISSUE TITLE
Support lazy loading to avoid crashes

### ISSUE THREAD

**Issue by Enngage** [julianpaulozzi/LiteDbExplorer#10]
Hi there,

Thanks for your work on this viewer! I've just started using it Yesterday and would love to continue to do so, but unfortunately I'm experiencing constant crashes because of memory / data management. I'm using LiteDb to store huge amounts of data that I don't want in my SQL server. Introducing some lazy loading should most probably help with most of these issues.

Ps: this applies both of items in the collection and **inner denormalized items** inside items.

Thanks again!

**Comment by julianpaulozzi** [comment]
See: #12.
Thanks.

**Comment by julianpaulozzi** [comment]
The document TreeView already has lazy loading and the grid does not have expansion nodes to lazy loading. 
Speaking of the WPF world you must be talking about 'Data Virtualization'?
If you can try this version to see if it's better: [LiteDbExplorer_prev_0.8.0_0312](https://github.com/julianpaulozzi/LiteDbExplorer/blob/master/wip-preview/LiteDbExplorer_prev_0.8.0_0312.zip)

In it we have:
- VirtualizingStackPanel in grid and treeview.
- ScrollViewer Deferred.
- Full structural UI rewrite.

Both can cause other problems.

This is a pre-release. We’ll point out that this release is identified as non-production ready.

**Comment by Enngage** [comment]
Thanks! I'll be using this and see how that works. So far, it seems good
and definitely a step in the right direction.
