### ISSUE TITLE
Help wanted: Need a real large database for 'local only' dev and tests

### ISSUE THREAD

**Issue by julianpaulozzi** [julianpaulozzi/LiteDbExplorer#12]
I need a more real-world large database file to check and test performance and memory issues (like #10 and #11). 
The ones I use today do not seem to be large enough.

The file will be for local use and development only, will not be added to the repository and will not be shared in any other way.

Any question, comment on this issue.
Thanks.

**Comment by informacione** [comment]
How can I give you my actual file?

**Comment by julianpaulozzi** [comment]
You could share via Google Drive to the email julianpaulozzi@gmail.com.
Thanks.

**Comment by informacione** [comment]
I shared the file and just tried that specific file with the pre-release app.  
It exports the data from that specific file perfectly but I am not able to see data in main right window. 
Export works by clicking table on the left.

**Comment by julianpaulozzi** [comment]
Thanks @informacione. 
As soon as possible I reply on #10 and #11 related issues.
