### ISSUE TITLE
fix drap file to left panel.

### ISSUE THREAD

**Issue by a44281071** [julianpaulozzi/LiteDbExplorer#18]
UI re-designed? Lost important features. Such as drop some file to window open it.

**Comment by julianpaulozzi** [comment]
I tested the older and the current version, drag and drop files on the left navigation panel works on both, drag anywhere in the window does not.

If you have lost something or you have more information and/or questions please comment or open a new one.

Just be sure to follow the [Issue Reporting Guidelines](https://github.com/julianpaulozzi/LiteDbExplorer#issue-reporting-guidelines) from now on.
