### ISSUE TITLE
Poor performance - 0.8.1.0

### ISSUE THREAD

**Issue by a44281071** [julianpaulozzi/LiteDbExplorer#19]
# introduction:
Select an document item in list view, main window will be fake death for 40 second. (to load DataPreview?) 
Select an field item in data preview, main window will be fake death for 10 second, too.
Change window size, when data preview visible also fake deth, too.
Max field string is XML content (should I move it to FileStorage?)

# detail:
LiteDbExplorer version: 0.8.1.0 portable
PC: 【I5 M560 2.67GHz】【6G DDR3】【HDD】 
Document: FileSize=100KB, DocumentCount=1419, HierarchicalDepth=4, MaxStringLength(XML)=183,392

**Comment by julianpaulozzi** [comment]
Yes sure a string of this size will hang the UI.

Optimizations related to performing operations outside the UI thread are being considered and string expansion as the issue reported in #14 to.

The fact that LiteDB is synchronous and the [AvalonEdit](http://avalonedit.net/) used to view json does heavy work to display "json" with syntax highlighting must have its impact too.
