### ISSUE TITLE
Date Time Display Format

### ISSUE THREAD

**Issue by neilsb** [julianpaulozzi/LiteDbExplorer#23]
This is a: Bug Report (arguably)

Version: 0.8.2.0

Steps to reproduce: View a document with a Date Time

What is expected: DateTime in Local or Universal Format

What is actually happening: DateTime displayed in Forced US Format

Any additional comments: 

Presently the DateTime values within the app are shown in US Date format, irrespective of the users culture and locale settings, due to the use of the `CultureInfo.InvariantCulture` in the ToString calls.

It would be a better user experience if dates were displayed in the ISO format, or use the users currently system Culture settings.  Allowing the user to choose to display format in the settings would be even better.

Same formatting concerns also exist for other data types (e.g. French use a "," instead of a "." in decimals) which would also be worth considering.

**Comment by julianpaulozzi** [comment]
I understand. This application tends to be a 'developer centric' where InvariantCulture should not be a problem for interpretation.
For some historical reason InvariantCulture is US Culture as well as all the rest of the application UI.
If you have seen any inconsistency of date formats outside of this common InvariantCulture format please report.
For now I will close this because there are no plans for localization/globalization at the moment.
Any Pull request for review is welcome.

**Comment by neilsb** [comment]
One thing that is inconsistent is that the Document Editor screen *does* use the current Windows Locale settings. 

The Date Picker shows the Windows Locale "Long Date Format" and the number entry is displayed (and requires to be entered) in the current Locale  (e.g.  "4.25" in US Locale, when switched to French is shown in the editor as "4,25".   Entering "4.25" and attempting to save results in the value "4" being saved).

Would you accept a pull request where the application was updated to use the current windows locale for Display and Entry of data?  I would argue that with a Developer centric user base, they are likely to be knowledgable enough about Locales and have their computer set up for how they wish to use it.

I would also like to include (within the settings) a specific option to allow the Date Times to be shown as a standard ISO 8601 Format.

**Comment by julianpaulozzi** [comment]
Yes of course, go ahead if you want to send a pull request.
Must have everything needed for this in the project including [Humanizer](https://github.com/Humanizr/Humanizer) in case you want something more.
About configuration can add this on app Properties -> Settings and follow with export ISettingsEditor and IAutoGenSettingsView, that uses [PropertyTools](https://github.com/PropertyTools/PropertyTools) to automatically create the UI using attributes.
