### ISSUE TITLE
Problem to run LiteDbExplorer

### ISSUE THREAD

**Issue by Blackleones** [julianpaulozzi/LiteDbExplorer#3]
Hi, 
I'm trying to launch LiteDB_7.0.2 but Windows returns "windows cannot access the specified device path or file you may not have appropriate permissions" error.  
I have tried to run LiteDB as Administrator but it not works. Same error even on LiteDB_7.0.1

**Comment by julianpaulozzi** [comment]
I could not reproduce the problem. It worked?
