### ISSUE TITLE
Enhancement Request: Save/Load Query Files

### ISSUE THREAD

**Issue by mzhukovs** [julianpaulozzi/LiteDbExplorer#33]
This is a fantastic tool. Thanks much. Wondering if you had any plans to allow for saving/loading of queries within the tool? Would be convenient instead of copying/pasting.

**Comment by julianpaulozzi** [comment]
Look to commit d78c71f4a6407a56a51fe82ac1e6a546c701711d to see if it helps.
For now not persist the data, but on the way.

**Comment by mzhukovs** [comment]
Awesome!
