### ISSUE TITLE
Show timer on queries

### ISSUE THREAD

**Issue by MischaKr** [julianpaulozzi/LiteDbExplorer#38]
**This is a:** 
Feature Request

**Version:** 
- 8.4.4

**Describe the bug**
Showing a timer on how long a query/action takes on the database.
It can be interesting to see how long a query takes to execute on the database, currently this information isn't shown. 

Currently only the amount of records records are shown and the last performed query.

**Comment by julianpaulozzi** [comment]
This should not serve as performance metrics as it is relative to the computational power that performs.
But it's cool, I'll add.

**Comment by MischaKr** [comment]
Yeah I was thinking it just gives it a bit more polish.
