### ISSUE TITLE
Cannot edit _id

### ISSUE THREAD

**Issue by Delog-ru** [julianpaulozzi/LiteDbExplorer#39]
It seems it's impossible to edit _id field which would be very useful. I have classes with Id field of type uint but when I add record manually in LiteDbExplorer it automatically generates _id of incompatible type which I cannot delete nor edit. So it basically makes impossible to add new record in DB using LiteDbExplorer.

**Comment by Delog-ru** [comment]
Forget to mention I was talking about version 0.8.4.5 which is last. Older version 0.8.4.2 is ok, it allows editing and deleting _id field. Was that feature intentionally removed?

**Comment by julianpaulozzi** [comment]
Yes, this has been intentionally removed as it causes problems, bugs, data and references loss....

But soon I will add a configuration option to allow editing ids for those who want to explicitly take the risk.

I will think of a more dynamic way to deal with this in the future.
