### ISSUE TITLE
Update not working on "shared" mode

### ISSUE THREAD

**Issue by Ofiraf** [julianpaulozzi/LiteDbExplorer#42]
**This is a:** (required)  
Bug Report

**Version:** (required)  
0.8.5.1

**Describe the bug**
Update\Save document editing is not working when working with "shared" mode in the database selection

**Steps to reproduce:** (required) 
Open doc, edit click ok, open the doc again -> data not saved

**What is actually happening:** (required)  
- What is actually happening?

**Any additional comments:** (optional)  
- Any additional comments 

**Screenshots** (optional)

**Comment by julianpaulozzi** [comment]
As informed in issue #41 the option to open the bank in a shared way would be added but with no guarantee that it would not cause problems.
Precisely to avoid issues I had changed the connection way.
I did a test and had no problem updating the registry but the database was not being used by any other process.
Maybe you are editing old records or who have lost the reference in Explorer.
