### ISSUE TITLE
Incorrectly reporting its version number 0.8.5.2 ... says it's v0.8.5.1

### ISSUE THREAD

**Issue by nathanwienand** [julianpaulozzi/LiteDbExplorer#43]
**This is a:**
Bug Report

**Version:**
0.8.5.2

**Steps to reproduce:**
download and install v0.8.5.2 from releases page

**What is expected:**
that the app knows it is version 0.8.5.2

**What is actually happening:**
it thinks it is version 0.8.5.1 and prompts for updates ... after updating I'm still on version 0.8.5.1 :)
I think the version tag within the software is incorrectly set in this build. :)

**Any additional comments:**
I love this product guys keep up the good work, and thanks so much !!!

**Comment by julianpaulozzi** [comment]
Fixed incorrect version in release zip.

You can check for updates manually in 'Help' menu to get the updated version correctly.

Thanks for reporting.
