### ISSUE TITLE
Unable to click on Refresh button when switching between table tabs.

### ISSUE THREAD

**Issue by darcome** [julianpaulozzi/LiteDbExplorer#44]
**This is a:** (required)  
Bug Report

**Version:** (required)  
- 0.8.5.2

**Describe the bug**
When I have a table tab open and open another table tab, and then switch back to the previous table tab, I cannot click Refresh because it is grayed out.

**Steps to reproduce:** (required) 
- Open two or more table tabs by double clicking on table names on the left, and then switch between the opned tabs and notice that Refresh button is grayed out.

**What is expected:** (required)  
- I would expect to be able to click on the Refresh button when I switch between table tabs.

**What is actually happening:** (required)  
- I am unable to click on the Refresh button when I switch between table tabs.

**Comment by julianpaulozzi** [comment]
You must have active command when setting the focus in list with mouse.

It is related to this issue: https://github.com/ButchersBoy/Dragablz/issues/168

Let me know if this works?

**Comment by darcome** [comment]
Yes, I can confirm that's the problem and if I click on the tab again, I can press the Refresh button.

Given that you use a library that's not been updated since 2018, I suppose this bug will never be resolved, correct?

**Comment by julianpaulozzi** [comment]
Probably by the library not.
Then I’ll try an approach to set the focus manually.
I just can't guarantee if it will work well, WPF's FocusManager and RoutedUICommand is kind of rebellious.

**Comment by darcome** [comment]
Hi, I have just checked 0.8.5.3 and confirm that the refresh button is now always clickable.
