### ISSUE TITLE
Can you build up a Mac version?

### ISSUE THREAD

**Issue by winsonet** [julianpaulozzi/LiteDbExplorer#47]
I love the LiteDb, but I can't find any explorer for Mac OS, if you can build a Mac version that will be great!

thanks!

**Comment by julianpaulozzi** [comment]
This project is built with WPF, a Windows only .NET Framework technology and not Mono compatible.
So it is not possible.

I started a prototype for Mac OS with native UI with Xamarin, but I have no plans to continue with this.

Thank you for enjoying the project and for comprehension.
