### ISSUE TITLE
Won't Open Database, No Error

### ISSUE THREAD

**Issue by shadyrat** [julianpaulozzi/LiteDbExplorer#48]
**This is a:**
Bug Report

**Version:**
0.8.6.1

**Steps to reproduce:**
I downloaded the release, ran the executable, and no matter how I try to open a database nothing happens.  I've tried using the 'Open' on the start page, File->Open in the menu, and closing the start page and dragging my database onto the form.

**What is expected:**
At bare minimum, I'd expect an error dialog or even an entry in the error log.  The error log is empty and there is no UI indication whatsoever as to what has happened.

**What is actually happening:**
There are no errors, no dialog, nothing.  All attempts to open the database simply act as though nothing happened.

**Any additional comments:**
The database I'm trying to open (and only one I have handy) was created using LiteDB v5.0.5.  It only has 4 collections and a couple dozen rows/documents.  It's 155,648 bytes in size.

**Comment by julianpaulozzi** [comment]
This only supports LiteDB **v4**.

Includes open error handling for incompatible versions < 4.

There is currently nothing about **v5** (nor file open error handling), there are plans to support version 5 sometime next year.

**Comment by shadyrat** [comment]
I missed that, sorry.  Thanks for the quick reply!
